cmake: fix building in debug mode
The build with -DCMAKE_BUILD_TYPE=Debug can ends with the error:

> In file included from luzer/counters.c:8:
> In file included from /usr/lib/llvm/20/bin/../../../../lib/clang/20/include/stdint.h:56:
> In file included from /usr/include/stdint.h:26:
> In file included from /usr/include/bits/libc-header-start.h:33:
> /usr/include/features.h:422:4: error: _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror,-W#warnings]
  422 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)

This happened because optimizations must be enabled when
compiler option `_FORTIFY_SOURCE` is enabled. CMake has four
build types: Release, Debug, RelWithDebInfo, MinSizeRel and only
Debug build type disables optimizations. The patch applies
compiler hardening flags to all targets, enables `_FORTIFY_SOURCE`
option only for non-debug builds and fixes errors generated by
enabled compiler options.

Fixes #54